name: nrdlojas_v3
description: NRD Lojas V3 - Flutter UI with Android Jetpack Compose native integration.
publish_to: "none"
version: 3.4.011+304011

environment:
  sdk: ">=3.9.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  rive: ^0.14.11
  firebase_core: ^4.13.0
  cloud_firestore: ^6.8.0
  firebase_auth: ^6.5.7
  shared_preferences: ^2.5.5
  url_launcher: ^6.3.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/rive/
